import random

def guess(limit):

    '''
    
    Method generates a random number 
    User tries to guess the number
    Method provides feedback
    User needs to guess the correct number
    
    '''

    random_number = random.randint(1,limit)
    guess = 0

    while guess != random_number:
        guess = int(input(f'Please guess a number between 1 and {limit}:\n'))
        if guess < random_number:
            print("Oops! The guess is too low. Please try again!")
        elif guess > random_number:
            print("Oops! The guess is too high. Please try again!")
    if guess == random_number:
        print(f"Yay! You guessed right. You guessed the number {random_number}")
        print("Thank you for playing with our bot")

def guessComputer(limit):

    '''
    
    User thinks of a number between 1 to 100. 
    Method guesses a number
    User inputs feedback depending on the guess
    Method will guess the correct number based on the feedback

    '''

    low = 1 
    high = limit
    userFeedback = ''
    while userFeedback != 'c':
        guess = random.randint(low,high)
        userFeedback = str(input(f"Is the guess {guess} correct? If correct type 'c' else enter 'n':\t"))
        if userFeedback == 'l':
            low = guess
        elif userFeedback == 'h':
            high = guess
    print(f"Yay! The bot guessed the number {guess} right!. Thanks for playing!")

if __name__ == '__main__':

    '''

    Main Method: 

    The user is prompted to choose the game he wants to play, the options are as follows
    1. User guesses a number generated by the Computer
    2. Computer guesses the number the user thinks before hand

    '''

    which_game = int(input("Which Game do you want to play, Pleae enter Option 1 or 2: \t"))

    if which_game == 1:
        guess(10)
    else:
        guessComputer(100)